/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.phototbooth_coba;

import java.io.File;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Filter extends javax.swing.JInternalFrame {

    /**
     * Creates new form Filter
     */
    public Filter() {
        initComponents();
        tampil_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_filter = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        Tabel_filter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama Filter", "Keterangan"
            }
        ));
        Tabel_filter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_filterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_filter);

        jButton1.setText("Choose Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Keterangan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Umum", "Login" }));

        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bersih");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, 262, Short.MAX_VALUE))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser flch = new JFileChooser();
        flch.showOpenDialog(null);
        File fl = flch.getSelectedFile();
            jTextField1.setText(fl.getName());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fl = (String) jTextField1.getText();
        String ket = (String) jComboBox1.getSelectedItem();
        
         if(fl.equals("")|| ket.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Isi data dulu");
        }else if (ket.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Isi data dulu");
        }else{
        try{
            String Q = "INSErT INTO filter (Filter,Keterangan) VALUES ('"+fl+"','"+ket+"')";
                java.sql.Connection Vconn = (Connection)KoneksiDB.KonfigDB();
                java.sql.PreparedStatement s = Vconn.prepareStatement(Q);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Tambah Data gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel();
        bersih();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String fl = jTextField1.getText();
        String ket = (String) jComboBox1.getSelectedItem();
        
        try{
            String query = "DELETE FROM filter WHERE Filter = '"+fl+"'";
            
            Connection Vconn = (Connection)KoneksiDB.KonfigDB();
            
            java.sql.PreparedStatement tsm = Vconn.prepareCall(query);
            
            tsm.execute();
            
            JOptionPane.showMessageDialog(null, "Hapus berhasil");
            
            tampil_tabel();
            bersih();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hapus glagla");
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Tabel_filterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_filterMouseClicked
        // TODO add your handling code here:
        int baris = Tabel_filter.rowAtPoint(evt.getPoint());
//        int kolom = tabel_karyawan.columnAtPoint(evt.getPoint());
        
        
        
        String fl = Tabel_filter.getValueAt(baris,1).toString();
        jTextField1.setText(fl);

        String ket = Tabel_filter.getValueAt(baris,2).toString();
        jComboBox1.setSelectedItem(ket);
    }//GEN-LAST:event_Tabel_filterMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampil_tabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No");
        tb.addColumn("Nama Filter");
        tb.addColumn ("Keterangan");
        
        
        try{
            int counter = 1;
            String query = "SELECT * FROM filter";
            
            java.sql.Connection vconn = (Connection)KoneksiDB.KonfigDB();
            
            java.sql.Statement s = vconn.createStatement(); 
            
            java.sql.ResultSet r = s.executeQuery(query);
            
            while(r.next()){
                tb.addRow(new Object[]{
                    counter++,r.getString(2),r.getString(3)
                });
            }
            Tabel_filter.setModel(tb);
        }catch(Exception e){
        }
    }
    
    private void bersih(){
    jTextField1.setText("");
    jComboBox1.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
